### PR TITLE
Add comment, parent sharing, and hollow tag icons

### PR DESCRIPTION
**Pull request by technizor**

### CODE REVIEW

**Comment by dlockhart** [comment]
@technizor could you change the names to "-filled" instead of "fill"? That way they're consistent with "flag-filled", "pin-filled", "subscribe-filled" and "bookmark-filled".

**Comment by dlockhart** [comment]
@technizor are you hoping to use these new icons in the monolith, a FRA that uses hybrid Polymer elements or a FRA that uses Polymer 1.x elements? Because depending on the answer, these may also need to go into the `3.x` branch (for Polymer 1.x elements and the monolith).

**Comment by technizor** [comment]
@dlockhart These icons are going to be used in (Port)Folio and Parent Portal, specifically in the evidence tile Polymer 1.x element.

**Comment by dlockhart** [comment]
@technizor OK cool, so once this merges into master, you'll want to make the same change in the `3.x` branch, which is currently the Polymer 1.x version.

**Pull request merged**
