### PR TITLE
US93814 add manage dates icons

### PR DESCRIPTION
**Pull request by cgalvind2l**

### CODE REVIEW

**Comment by njostonehouse** [comment]
To help with sorting the icons, it might help to have a common prefix for related icons like `dates-bulk-edit` and `dates-offset`.

**Comment by cgalvind2l** [comment]
Good idea!

**Comment by cgalvind2l** [comment]
I assume I have to manually update http://search.dev.d2l/source/xref/Lms/core/lp/framework/web/D2L.LP.Web/UI/Html/Icons/IconTypes.cs as well?

**Comment by dlockhart** [comment]
Yeah, that's a manual process.

**Comment by cgalvind2l** [comment]
Thanks all! ...could someone merge for me? :)

**Comment by dlockhart** [comment]
@cgalvind2l merged and created release `4.8.0`.

**Pull request merged**
