### PR TITLE
US79972: Darken all icons to ferrite.

### PR DESCRIPTION
**Pull request by njostonehouse**

### CODE REVIEW

**Comment by dlockhart** [comment]
Oh wow, we're doing this eh?

**Comment by geurts** [comment]
As designed! Scary to me too, but I'll trust in the designs.

**Comment by dlockhart** [comment]
@njostonehouse the only thing I think is missing is that the README mentions tungsten and the HEX code a few times.

**Comment by njostonehouse** [comment]
There may also be screen caps that need updating, I haven't verified that yet.

**Pull request merged**
