### PR TITLE
Add thin chevron-down svg in tier1

### PR DESCRIPTION
**Pull request by mdulat**

### CODE REVIEW

**Comment by mdulat** [comment]
@dlockhart any ideas why travis-ci is failing here? I only see errors in libraries within node-modules, don't see where these are originating.

**Comment by dlockhart** [comment]
I have a guess. In `.travis.yml`, could you try forcing it to node version 9?

```
node_js:
- 9
```

**Comment by mdulat** [comment]
node 9 did it, thanks @dlockhart. Can you please merge this? I don't have the permissions.

**Comment by dlockhart** [comment]
Sure thing, merged and published as version `4.13.0`.

**Pull request merged**
