### PR TITLE
Experiment: Add galen tests for icons

### PR DESCRIPTION
**Pull request by awikkerink**

### CODE REVIEW

**Comment by awikkerink** [comment]
https://s3.amazonaws.com/sequence-viewer-artifacts/BrightspaceUI/icons/489/489.1/report.html

**Comment by awikkerink** [comment]
https://s3.amazonaws.com/sequence-viewer-artifacts/BrightspaceUI/icons/501/501.1/report.html

**Comment by awikkerink** [comment]
https://s3.amazonaws.com/sequence-viewer-artifacts/BrightspaceUI/icons/503/503.1/report.html

**Comment by awikkerink** [comment]
@capajon @dbatiste What are your thoughts about this? Does *d2l-galen-utils* make sense? Any suggestions? Or does Galen not work well with icons?

**Comment by dbatiste** [comment]
Hey Anthony, sorry for taking a few days to get back to this.  I have some mixed thoughts:

* I think pdiff tests definitely make sense for icons, to a certain extent.  
* Mostly interested in testing the stylistic aspects that we've configured: sizes, ltr/rtl, color overrides
* Interested in pdiff for `d2l-icon-button` and `d2l-icon-link`.  
* pdiff every icon? (concerned about maintaining... for every icon update, maybe no big deal?)
* Seems like lots of configuration required.  Is it possible to move some config to Galen utils?

**Comment by awikkerink** [comment]
Hey Dave, thanks for your feedback.

* I didn't want to do pdiff because it would involve a lot of maintenance.
* I know configuration is an issue. I would like to set some more defaults in d2l-galen instead of galen.config to simplify things. Any suggestions on what else I can move to Galen utils?

**Pull request closed without merging**
