### PR TITLE
US77021 Daylight flag icons colour change

### PR DESCRIPTION
**Pull request by ChrisKraljevicD2L**
Filled flag colour changed to `#CD2026`
Hollow flag colour changed to `#B9C2D0`

### CODE REVIEW

**Comment by dlockhart** [comment]
Are we sure we want this to apply to all flag icons? This would be the first icon that has a colour other than #72777a. Due to the way the Polymer icon sets work (they strip the colour so you can customize it), this also won't affect them. Another option would be to leave it as-is, but apply the colour by manually setting it in CSS for Brightspace.

**Comment by ChrisKraljevicD2L** [comment]
@ctwomey1 and I had a conversation with Rebecca this morning about that, she does want this to apply to all flag icons. I didn't know about stripping colour from icons, so I'm willing to implement this as a CSS change instead.

**Comment by dlockhart** [comment]
OK cool, makes sense. But yeah, this isn't going to work the way you're hoping because of the colour getting stripped. You'll need to implement it in CSS -- I can help if you need it offline outside of this PR.

**Comment by dlockhart** [comment]
@ChrisKraljevicD2L Hmm... it's been a while, this PR can likely be closed?

**Comment by ChrisKraljevicD2L** [comment]
@dlockhart Yup, I'll close it shortly

**Pull request closed without merging**
