### PR TITLE
Adding borderless play/pause/stop icons

### PR DESCRIPTION
**Pull request by rcausey**

### CODE REVIEW

**Comment by rcausey** [comment]
@dbatiste any idea why the travis build is failing?

**Comment by dbatiste** [comment]
I think there is a limitation with running Sauce on PR from forks because if this was allowed, anyone who forks could output the decrypted credentials (and use our paid Sauce minutes).  I'm not sure if there is a way around this.  @dlockhart ?

**Comment by dlockhart** [comment]
@dbatiste There is a way around this -- it's to use the [JWT add-on](https://docs.travis-ci.com/user/jwt) to encrypt the key. That'll give it a short-lived token to use instead, and Sauce supports it. We're already using this approach in at least [tables](https://github.com/BrightspaceUI/table/blob/master/.travis.yml#L13) and [ajax](https://github.com/BrightspaceUI/ajax/blob/master/.travis.yml#L9).

**Comment by dbatiste** [comment]
@rcausey : I've updated the sauce access key and username in the travis config.  You'll probably need to update with my changes to get Sauce working for your PR.

**Comment by rcausey** [comment]
@dbatiste cool, thanks!

**Pull request merged**
