### PR TITLE
Activity Feed Message Post icon

### PR DESCRIPTION
**Pull request by ctwomey1**

### CODE REVIEW

**Comment by dlockhart** [comment]
Agreed. What's the underlying purpose of the icon? Would it be used like Noel suggested for all "messages" being posted somewhere, irregardless of the destination being activity feed?

**Comment by ctwomey1** [comment]
I followed up with Sarah, the metaphor is "activity feed".  So it would be used in the context of things coming from activity feed.  Our first usage will be for activity feed message post bell notifications in the lms.

Would just activity-feed.svg, be ok?

**Comment by dlockhart** [comment]
Perfect, yeah then in that case I agree it should be `activity-feed.svg`.

You've got some conflicts, so you probably want to revert changes to the auto-generated stuff, rebase and then re-run `npm run build`.

**Comment by ctwomey1** [comment]
Settled on `feed.svg` as per @njostonehouse

**Pull request merged**
