### PR TITLE
Fix Paths

### PR DESCRIPTION
**Pull request by dlockhart**

### CODE REVIEW

**Comment by dlockhart** [comment]
Also the builder doesn't actually seem to be working -- if I change something and rebuild it doesn't do anything. Investigating...

**Comment by awikkerink** [comment]
I found it didn't work for node 10 for some reason. Seemed to work fine in node 8.10...

**Comment by dlockhart** [comment]
I think I found the problem -- I'm going to fix it in the hybrid branch and bring it over here.

**Comment by dlockhart** [comment]
Will re-open later

**Pull request closed without merging**
